# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: bucketName
  value: business.corestepbank.com 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# - task: S3Upload@1
#   inputs:
#     awsCredentials: 'CorestepAwsCredential'
#     regionName: 'us-east-1'
#     bucketName: 'business.corestepbank.com'
#     sourceFolder: 'dist'
#     # globExpressions: ['js/**','css/**','img/**','fonts/**','index.html','favicon.ico']
#     globExpressions: '*!(config)/**'
#     # globExpressions: '*(js/**/*|css/**/*|img/**/*|fonts/**/*|index.html|favicon.ico)'
#     # globExpressions: '!config/**'. js/**|css/**|img/**|fonts/**|
#     filesAcl: 'authenticated-read'
#     createBucket: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'CorestepAwsCredential'
    regionName: 'us-east-1'
    bucketName: $(bucketName)
    sourceFolder: 'dist'
    globExpressions: '*'
    filesAcl: 'authenticated-read'
    createBucket: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'CorestepAwsCredential'
    regionName: 'us-east-1'
    bucketName: $(bucketName)
    sourceFolder: 'dist'
    globExpressions: 'js/**'
    filesAcl: 'authenticated-read'
    createBucket: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'CorestepAwsCredential'
    regionName: 'us-east-1'
    bucketName: $(bucketName)
    sourceFolder: 'dist'
    globExpressions: 'css/**'
    filesAcl: 'authenticated-read'
    createBucket: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'CorestepAwsCredential'
    regionName: 'us-east-1'
    bucketName: $(bucketName)
    sourceFolder: 'dist'
    globExpressions: 'img/**'
    filesAcl: 'authenticated-read'
    createBucket: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'CorestepAwsCredential'
    regionName: 'us-east-1'
    bucketName: $(bucketName)
    sourceFolder: 'dist'
    globExpressions: 'fonts/**'
    filesAcl: 'authenticated-read'
    createBucket: true

- task: S3Upload@1
  inputs:
    awsCredentials: 'CorestepAwsCredential'
    regionName: 'us-east-1'
    bucketName: $(bucketName)
    sourceFolder: 'dist'
    globExpressions: 'config/**'
    filesAcl: 'authenticated-read'
    createBucket: true
